version: '3'
services:
  app:
    container_name: app
    build:
      context: .
    command: npm run start
    networks:
      - app-network
    ports:
      - '3001:3001'
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules

networks:
  app-network:
    driver: bridge
