name: Sonar Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16^]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build-DB
        run: docker-compose build

      - name: Stop docker
        run: docker-compose stop

      - name: Run docker and tests
        run: docker-compose up -d && docker ps && docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app && docker logs app

      - name: Cypress run
        run: echo 'Vai rodar o cypress!!' && docker ps && docker exec app ls && docker exec app npm run test:headless
        #run: echo 'Vai rodar o cypress!!' && docker exec app docker ps && docker exec app npm run test:headless

      #   cypress-run:
      # runs-on: ubuntu-latest
      # # Docker image with Cypress pre-installed
      # # https://github.com/cypress-io/cypress-docker-images/tree/master/included
      # container: cypress/included:4.11.0
      # steps:
      #   - name: Checkout 🛎
      #     uses: actions/checkout@v1

      #   # normally we would NOT need to install NPM dependencies
      #   # but in this repo we are using additional plugins listed in package.json
      #   # thus we need to install them
      #   - name: Install dependencies 📦
      #     # we could simply run "npm ci" but that would not cache dependencies
      #     # thus we can use this 3rd party action
      #     uses: bahmutov/npm-install@v1

      #   - name: Run tests 🧪
      #     run: cypress run --record
      #     env:
      #       # pass the Dashboard record key as an environment variable
      #       CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #   run: docker exec app pwd && ls && npx cypress run --component --config video=false
      #$$ docker exec app $$ ls && pwd && npx cypress run --component --config video=false
      #  && npm run test:headless
      #$(npm bin)/cypress
      # - name: Headless Chrome
      #   uses: cypress-io/github-action@v4
      #   timeout-minutes: 10
      #   with:
      #     start: npm run test:headless
      #     browser: chrome
      #     headless: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
