name: Sonar Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16^]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build docker
        run: docker-compose build

      - name: Stop docker
        run: docker-compose stop

      - name: Run docker
        run: docker-compose up -d && docker ps && docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app && docker logs app

      - name: Cypress run
        run: echo 'Vai rodar o cypress!!' && docker ps && docker exec app ls && docker exec app npm run test:headless

      - name: Eslint run
        run: echo 'Vai rodar o eslint!!' && docker exec app npx eslint src/*.js -f json -o ./report/eslint-report.json || true
        #run: echo 'Vai rodar o eslint!!\n' && docker exec app npx eslint src/*.js -f ./eslint-formatter-to-sonarcloud.js -o ./report/eslint-report.json || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
