name: Node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16^]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build-DB
        run: docker-compose build

      - name: Stop docker
        run: docker-compose stop

      - name: Run docker and tests
        run: docker-compose up -d && cd tests && pwd && npm install && ping -c 5 172.18.0.3 && docker ps && docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app && docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sonarqube && npm run test
