name: Sonar Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16^]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build docker
        run: docker-compose build

      - name: Stop docker
        run: docker-compose stop

      - name: Run docker
        run: docker-compose up -d && docker ps && docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' app && docker logs app

      - name: Cypress run
        run: echo 'Vai rodar o cypress!!' && docker ps && docker exec app ls && docker exec app npx clear-npx-cache && docker exec app npm run test:headless

      - name: Eslint run
        run: echo 'Vai rodar o eslint!!' && docker exec app npx eslint src/*.js -f ./eslint-formatter-to-sonarcloud.js -o ./report/eslint-report-formated.json || true && docker exec app cat ./report/eslint-report-formated.json || true && docker exec app npx eslint src/*.js -f json -o ./report/eslint-report.json || true && docker exec app cat ./report/eslint-report.json || true

      - name: copy files to workspace
        # https://forums.docker.com/t/is-there-a-way-to-copy-a-file-from-an-image-to-the-local-filesystem-without-running-a-container/2841
        run:
          ls ${{ github.workspace }}/report 
          sed -e "s;/home/node/app;/github/workspace/;g" ./report/eslint-report-formated.json > ./report/eslint-report-formated.temp 
          mv ${{ github.workspace }}/eslint-report-formated.temp ${{ github.workspace }}/eslint-report-formated.json 
          sed -e "s;/home/node/app;/github/workspace/;g" ./report/eslint-report.json > ./report/eslint-report.temp 
          mv ${{ github.workspace }}/eslint-report.temp ${{ github.workspace }}/eslint-report.json
          # ls ${{ github.workspace }}/report && docker exec app pwd && docker cp app:/github/workspaceapp/report/*.* ${{ github.workspace }}/douglas
        securityContext:
          privileged: true

        workingDir: $(workspaces.source.path)
        script: |
          ls ${{ github.workspace }}/report 
          sed -e "s;/home/node/app;/github/workspace/;g" ./report/eslint-report-formated.json > ./report/eslint-report-formated.temp 
          mv ${{ github.workspace }}/eslint-report-formated.temp ${{ github.workspace }}/eslint-report-formated.json 
          sed -e "s;/home/node/app;/github/workspace/;g" ./report/eslint-report.json > ./report/eslint-report.temp 
          mv ${{ github.workspace }}/eslint-report.temp ${{ github.workspace }}/eslint-report.json
        securityContext:
          privileged: true
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
